development:
    bucket_name: doomhub
    access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
    aws_secret_access_key: <%= ENV['S3_SECRET_KEY_ID'] %>

production:
    bucket_name: doomhub
    aws_access_key: <%= ENV['S3_ACCESS_KEY_ID'] %>
    aws_secret_access_key: <%= ENV['S3_SECRET_KEY_ID'] %>